site_name: My Docs

theme:
  name: material

nav:
  - index.md
  - references.md
  - tutorials.md
  - explanation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

